### ISSUE TITLE
Intro "how to play" not shown correctly

### ISSUE THREAD

**Issue by Hexaae** [jotd666/tetris#2]
I let the intro roll and found the "how to section" doesn't show up correctly:

<a href="https://ibb.co/8xDWTt8"><img src="https://i.ibb.co/3FyDGQh/image.png" alt="image" border="0"></a>

Looks like every instruction frame gets overlapped over previous one...

**Comment by jotd666** [comment]
You're perfectly right. I've tried to fix that issue but no luck yet.

**Comment by jotd666** [comment]
transcode issue, carry flag wrongly cleared, found after 1 hour efficient investigating. Excellent!
